### ISSUE TITLE
HFValidationError when loading the model

### ISSUE THREAD

**Issue by jrivd** [huggingface/setfit#94]
Hi there! I am trying to load a model I have stored at Google Drive for inferencing:

```
# Load SetFit model
tuned_model = SetFitModel.from_pretrained("/content/drive/My Drive/models/tuned-model")
# Run inference
tuned_model(["i didnt feel humiliated", "i feel romantic too", "im grabbing a minute to post i feel greedy wrong"])
```

But I get the following error:

`
HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/content/drive/My Drive/models /tuned-model'. Use repo_type argument if needed.
`

it works however when I load it from the same script in which I have saved it, by:

```
# Save trained model to disk
trainer.model.save_pretrained("/content/drive/My Drive/models/tuned-model")
```

What can be the problem? Can't just I save/load from pretrained to Google Drive?

Many thanks in advance for your support and terrific work.

**Comment by lewtun** [comment]
Hey @jrivd can you provide a code snippet / Colab that reproduces the error? This will help debug what exactly is going on :)

**Comment by jrivd** [comment]
Hi @lewtun, thanks for your response. You can see the error in action here: https://colab.research.google.com/drive/10t9QmQEe7BHIQQ8XUmw1B37vPFRfORDK?usp=sharing
Many thanks!

**Comment by pdhall99** [comment]
I get the same error. When I try to load a locally saved model:
```python
from setfit import SetFitModel

model = SetFitModel.from_pretrained("/path/to/model-directory", local_files_only=True)
```
I get
```python
HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/path/to/model-directory'. Use `repo_type` argument if needed.
```

I think this could be solved by changing [these lines](https://github.com/huggingface/setfit/blob/a06be0efae1f71357aa357af8df42175f6adc91e/src/setfit/modeling.py#L84) from
```python
        if os.path.isdir(model_id) and MODEL_HEAD_NAME in os.listdir(model_id):
            model_head_file = os.path.join(model_id, MODEL_HEAD_NAME)
```
to something like
```python
        if os.path.isdir(model_id):
            if MODEL_HEAD_NAME in os.listdir(model_id):
                model_head_file = os.path.join(model_id, MODEL_HEAD_NAME)
            else:
                model_head_file = None
```

**Comment by Mouhanedg56** [comment]
I saved a trained model on local path. I can't see anything wrong when loading the model using `from_pretrained` with correct path.

This error appears when you try to load a model from a nonexistent local path which have more than 1 backslash `\` with `local_files_only=True`.

- if we pass a nonexistent path:
  - if path is in the form 'repo_name' or 'namespace/repo_name': `ModelHubMixin.from_pretrained` will throw `FileNotFoundError`.
  - else: `ModelHubMixin.from_pretrained` will throw a `HFValidationError` because the path does not exist locally and is not in the expected hub form.
- if we pass an existing local folder with no body: SentenceTransformer will throw an `OSError: /path/to/your/model does not appear to have a file named config.json`
- if we pass an existing folder with a body and head: no issue in this case
- if we pass an existing folder with a body with no head: `SetFitModel._from_pretrained` throws `HFValidationError` not catched by try/except. Since the expected behaviour in SetFit `_from_pretrained` classmethod is to initialise classification head with random weights when the MODEL_HEAD_NAME is not found, this can be considered as a bug.

@pdhall99 's suggestion looks fixing the issue and follows the same logic in the `ModelHubMixin.from_pretrained`: 

- if folder exists:
  - if model head file exists => `model_head_file = os.path.join(model_id, MODEL_HEAD_NAME)` else `None` => initialise classification head with random weights
- else: look for the model head in the hub using `hf_hub_download`.

**Comment by jrivd** [comment]
Many thanks for your comments, @pdhall99 and @Mouhanedg56! I'll go over them carefully

**Comment by pdhall99** [comment]
Hi @sfernandes-gim, this change is not yet merged.

**Comment by lewtun** [comment]
Hi folks, we've just released a new version that include fixes to some of the above issues. For those still having troubles, could you please comment below with a code snippet for debugging?  Thanks!

**Comment by sfernandes-gim** [comment]
Thanks @lewtun this works fine with the latest release

**Comment by kryptec** [comment]
I recently ran into this problem, and after reading the above comments resolved it by giving the absolute path to the folder instead of the relative one. 

I'm not sure if this is a hugging face issue, or the cluster environment I'm working on, but I thought I would mention it here in case it helps anyone.

**Comment by lamtrinh259** [comment]
@kryptec thank you so much, I tried your method and gave it the absolute path, and apparently, it works now!

**Comment by FinnFrotscher** [comment]
I still get this error:
```pyton
peftmodelpath = "/notebooks/eva/model.bin"

model = PeftModelForCausalLM.from_pretrained(
    model, 
    peftmodelpath, 
    cache_dir=peftmodelpath, 
    local_files_only=True, 
    model_head_file=None
)
```
`HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/notebooks/eva/model.bin'. Use `repo_type` argument if needed.`

**Comment by ayseozgun** [comment]
Hello,

I am trying to read the hf model directly from s3 on sagemaker studio. I am also getting same 'HFValidationError' error. I am putting my code below:

`from transformers import T5Tokenizer, T5ForConditionalGeneration

# Specify the S3 URL to your model and tokenizer
model_url = "s3://bucketname/model/"

# Load the model and tokenizer from S3
tokenizer = T5Tokenizer.from_pretrained(model_url)
model = T5ForConditionalGeneration.from_pretrained(model_url)

# Now you can use the model and tokenizer for inference
input_text = "translate English to German: How old are you?"
input_ids = tokenizer(input_text, return_tensors="pt", truncation=True, padding=True, max_length=512)
input_ids.to("cuda")

outputs = model.generate(input_ids)
print(tokenizer.decode(outputs[0]))`


I am able to see the model by running below code on sagemaker, so i am sure the path is correct.

`s3 = boto3.client('s3')
# List all objects in the model folder from S3
s3_resource = boto3.resource('s3')
my_bucket = s3_resource.Bucket(bucket_name)
for object_summary in my_bucket.objects.filter(Prefix=''):
    file_path = object_summary.key
    file_name = os.path.basename(file_path)
    if file_name:
        print(file_name)`
        
        
  Can you please help me? Thanks :)

**Comment by bojanbabic** [comment]
In the Colab this happens if you mount drive. For some reason mounted path is not recognized. Instead, try having model in `/content`. This should solve issue of missing path.

**Comment by u1vi** [comment]
I hade the same issue in the local machine (not colab). I was using mounted drive. 

Creating a symlink to a folder (saving directory) to the working directory (where the training is going on) solved the issue for me. 
`ln -s existing_source_file optional_symbolic_link`

**Comment by Rakin061** [comment]
> In the Colab this happens if you mount drive. For some reason mounted path is not recognized. Instead, try having model in `/content`. This should solve issue of missing path.

Not working event loading model from /content. Have you solve this issue from your side ? @bojanbabic

**Comment by zheyaf** [comment]
I'm download the s3 files to `tempfile`, the temporary folder is not recognized as well

**Comment by reouvenzana** [comment]
I encountered the same error when working on my local machine. I solved it by using an absolute path to my model directory.

**Comment by gleb-t** [comment]
Ran into the same issue on `1.1.0` when providing an absolute path. Downgrading to `0.7.0` helped resolve the issue.
